# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{table-for}
  s.version = "0.0.15"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Hunter"]
  s.date = %q{2012-01-20}
  s.description = %q{table-for is a table builder for an array of objects, easily allowing overriding of how any aspect of the table is generated}
  s.email = %q{hunterae@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/views/table_for/_table_for.html.erb",
    "lib/table-for.rb",
    "lib/table_for/base.rb",
    "lib/table_for/engine.rb",
    "lib/table_for/helper_methods.rb",
    "lib/table_for/table_for.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/hunterae/table-for}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{table-for is a table builder for an array of objects, easily allowing overriding of how any aspect of the table is generated}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<table-for>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<building-blocks>, ["= 0.0.7"])
    else
      s.add_dependency(%q<table-for>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<building-blocks>, ["= 0.0.7"])
    end
  else
    s.add_dependency(%q<table-for>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<building-blocks>, ["= 0.0.7"])
  end
end

